module.exports = {
  VIEW_CHANGED: 'VIEW_CHANGED',
  TRIP_FORM_LOADED: 'TRIP_FORM_LOADED',
  AUTOCOMPLETE_CREATED: 'AUTOCOMPLETE_CREATED',
  MAIN_AUTOCOMPLETE_UPDATED: 'MAIN_AUTOCOMPLETE_UPDATED',
  INPUT_UPDATED: 'INPUT_UPDATED',
  DESTINATION_INPUT_UPDATED: 'DESTINATION_INPUT_UPDATED',
  DESTINATION_ADDED: 'DESTINATION_ADDED',
  REMOVE_BUTTON_TOGGLED: 'REMOVE_BUTTON_TOGGLED',
  DESTINATION_REMOVED: 'DESTINATION_REMOVED',
  FILTER_CHANGED: 'FILTER_CHANGED',
  TRIPS_FETCHED: 'TRIPS_FETCHED',
  DROPDOWN_TOGGLED: 'DROPDOWN_TOGGLED',
  TRIP_ADDED: 'TRIP_ADDED',
  TRIP_MODIFIED: 'TRIP_MODIFIED'
}
