module.exports = {
  VIEW_CHANGED: 'VIEW_CHANGED',
  VIEW_CALENDAR: 'VIEW_CALENDAR',
  TRIP_FORM_LOADED: 'TRIP_FORM_LOADED',
  AUTOCOMPLETE_CREATED: 'AUTOCOMPLETE_CREATED',
  MAIN_AUTOCOMPLETE_UPDATED: 'MAIN_AUTOCOMPLETE_UPDATED',
  VIEW_CREATE_TRIP: 'VIEW_CREATE_TRIP',
  INPUT_UPDATED: 'INPUT_UPDATED',
  DESTINATION_INPUT_UPDATED: 'DESTINATION_INPUT_UPDATED',
  CREATE_TRIP_DESTINATION_INPUT: 'CREATE_TRIP_DESTINATION_INPUT',
  DESTINATION_ADDED: 'DESTINATION_ADDED',
  FILTER_CHANGED: 'FILTER_CHANGED',
  TRIPS_FETCHED: 'TRIPS_FETCHED'
}
