module.exports = {
  VIEW_CHANGED: 'VIEW_CHANGED',
  VIEW_CALENDAR: 'VIEW_CALENDAR',
  TRIP_INFO_UPDATED: 'TRIP_INFO_UPDATED',
  AUTOCOMPLETE_CREATED: 'AUTOCOMPLETE_CREATED',
  UPDATE_CALENDAR_INPUT: 'UPDATE_CALENDAR_INPUT',
  VIEW_CREATE_TRIP: 'VIEW_CREATE_TRIP',
  TRIP_FORM_INPUT_UPDATED: 'TRIP_FORM_INPUT_UPDATED',
  CREATE_TRIP_DESTINATION_INPUT: 'CREATE_TRIP_DESTINATION_INPUT',
  DESTINATION_ADDED: 'DESTINATION_ADDED',
  FILTER_CHANGED: 'FILTER_CHANGED',
  TRIPS_FETCHED: 'TRIPS_FETCHED'
}
